# Generated by Django 2.1.2 on 2018-12-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privilege', '0002_auto_20181205_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privilege',
            old_name='rolegroup',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='privilege',
            name='action',
            field=models.CharField(default=1, max_length=32),
        ),
    ]
