# Generated by Django 2.1.2 on 2018-12-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privilege', '0004_auto_20181210_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolegroup',
            options={'verbose_name': '权限角色组', 'verbose_name_plural': '权限角色组'},
        ),
    ]
