# Generated by Django 2.1.2 on 2018-12-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privilege', '0005_auto_20181210_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='privilege',
        ),
    ]
