# Generated by Django 2.1.2 on 2019-01-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privilege', '0006_auto_20181210_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=12, verbose_name='角色'),
        ),
    ]
