# Generated by Django 2.1.2 on 2019-01-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privilege', '0007_auto_20190113_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
