# Generated by Django 2.1.2 on 2019-01-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crms9', '0002_auto_20190105_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDistrbute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, '正在跟进'), (2, '已报名'), (3, '三天未跟进'), (4, '15天未成单')], default=1)),
                ('memo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='classlist',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'depart__in': [1000]}, related_name='abc', to='crms9.UserInfo', verbose_name='任课老师'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'depart': 1000}, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='crms9.UserInfo', verbose_name='班主任'),
        ),
        migrations.AlterField(
            model_name='consultrecord',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'status': 2}, on_delete=django.db.models.deletion.CASCADE, to='crms9.Customer', verbose_name='所咨询客户'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crms9.Department', to_field='code', verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='customerdistrbute',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'depart_id': 1001}, on_delete=django.db.models.deletion.CASCADE, to='crms9.UserInfo', verbose_name='课程顾问'),
        ),
        migrations.AddField(
            model_name='customerdistrbute',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='crms9.Customer'),
        ),
    ]
